# Generated by Django 6.0.2 on 2026-10-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0029_pending_assignment_dismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(help_text='Short label, e.g. MICCAI, CVPR, NeurIPS.', max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('url', models.URLField(max_length=500)),
                ('parser', models.CharField(choices=[('miccai_json', 'MICCAI open-access JSON'), ('virtual_site_json', 'Conference virtual-site JSON'), ('cvf_html', 'CVF / ECVA open-access HTML'), ('html_selectors', 'Generic HTML (CSS selectors)'), ('html_links', 'Generic HTML (title-like links)')], max_length=30)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Parser options as JSON, e.g. {"href_contains": "eccv_2024"}. See the guide below the list.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never synced'), ('ok', 'OK'), ('empty', 'No papers found'), ('error', 'Error')], default='never', max_length=10)),
                ('last_message', models.CharField(blank=True, default='', max_length=500)),
                ('paper_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['conference', '-year'],
                'constraints': [models.UniqueConstraint(fields=('conference', 'year', 'url'), name='unique_proceedings_source')],
            },
        ),
        migrations.CreateModel(
            name='ProceedingsPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='bot_engine.proceedingssource')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
